#!/bin/bash -e

#©keithhedger Tue 3 Feb 12:04:53 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

passwd root

if [ $USESYSTEMD -eq 0 ];then
	sed -i 's@/lib/systemd/systemd-udevd@/lib/udev/udevd@' "/etc/rc.d/init.d/udev"
	sed -i 's@/bin/udevadm@/sbin/udevadm@g' "/etc/rc.d/init.d/udev"
	sed -i 's@/bin/udevadm@/sbin/udevadm@g' "/etc/rc.d/init.d/udev_retry"
	sed -i 's@/lib/udev/udevd@/sbin/udevd@g' "/etc/rc.d/init.d/udev"
	/sbin/udevadm hwdb --update
	chmod +x /lib/udev/init-net-rules.sh
	/lib/udev/init-net-rules.sh
else
	ln -s /dev/null /etc/systemd/network/99-default.link
fi

save_lib="ld-2.33.so libc-2.33.so libpthread-2.33.so libthread_db-1.0.so"

cd /lib

for LIB in $save_lib; do
    objcopy --only-keep-debug $LIB $LIB.dbg 
    strip --strip-unneeded $LIB
    objcopy --add-gnu-debuglink=$LIB.dbg $LIB 
done    

save_usrlib="libquadmath.so.0.0.0 libstdc++.so.6.0.28 libitm.so.1.0.0 libatomic.so.1.2.0" 

cd /usr/lib

for LIB in $save_usrlib; do
    objcopy --only-keep-debug $LIB $LIB.dbg
    strip --strip-unneeded $LIB
    objcopy --add-gnu-debuglink=$LIB.dbg $LIB
done

unset LIB save_lib save_usrlib

find /usr/lib -type f -name "*.a" -exec strip --strip-debug {} ';'
find /lib /usr/lib -type f -name "*.so*" ! -name \*dbg -exec strip --strip-unneeded {} ';'
find /{bin,sbin}/ /usr/{bin,sbin,libexec}/ -type f -exec strip --strip-all {} ';'
find /usr/lib /usr/libexec -name "*.la" -delete
find /usr -depth -name $(uname -m)-lfs-linux-gnu\* | xargs rm -rf

rm -rf /tools

exit 0