#!/bin/bash -e

#©keithhedger Sun 22 Dec 19:34:30 GMT 2019 kdhedger68713@gmail.com

cd /LFSPkgBuildScripts/system/linuxheaders
./linuxheaders.LFSBuild up
	
cd /LFSPkgBuilds/LFSPkgBuildScripts/system/glibc
./glibc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/binutils
./binutils.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/coreutils
./coreutils.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/util-linux
./util-linux.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/gmp
./gmp.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/mpfr
./mpfr.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/mpc
./mpc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/gcc
./gcc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/kernel
./kernel.LFSBuild up
./firmware.LFSBuild up

DEPENDS="Man-pages-5.02 Zlib-1.2.11 File-5.37 M4-1.4.18"
lfspkg -B "$DEPENDS"

cd /LFSPkgBuildScripts/system/readline
./readline.LFSBuild install

DEPENDS="Bc-2.1.3
Shadow-4.7
Bzip2-1.0.8
Pkg-config-0.29.2
Ncurses-6.1
attr-2.4.48
acl-2.2.53
libcap-2.27
Sed-4.7
Psmisc-23.2
Iana-Etc-2.30
Bison-3.4.1
Flex-2.6.4
Grep-3.3
Bash-5.0
Libtool-2.4.6
GDBM-1.18.1
gperf-3.1
Expat-2.2.7
Inetutils-1.9.4
Perl-5.30.0
XML-Parser-2.44
intltool-0.51.0
Autoconf-2.69
Automake-1.16.1
xz-5.2.4
Kmod-26
Gettext-0.20.1
Libelf-0.177
Libffi-3.2.1
OpenSSL-1.1.1
python3-3.7.4
Ninja-1.9.0
Meson-0.51.1
Check-0.12.0
Diffutils-3.7
Gawk-5.0.1
Findutils-4.6.0
Groff-1.22.4
GRUB-2.04
Less-551
Gzip-1.10
IPRoute2-5.2.0
Kbd-2.2.0
Libpipeline-1.5.1
Make-4.2.1
Patch-2.7.6
Man-DB-2.8.6.1
Tar-1.32
Texinfo-6.6
Vim-8.1.1846
Procps-ng-3.3.15
E2fsprogs-1.45.3
Sysklogd-1.5.1
eudev-3.2.8
Wget-1.20.3
unzip-6.0
Init-For-LFS-0.0.5
GPM-1.20.7
Links-2.19"
lfspkg -B "$DEPENDS"

exit 0
#do this manually
bash
sudo lfspkg -u readline "/LFSBuiltPackages/9.0/SYSTEM/readline-8.0-1_SYSTEM_LFSPKG.tar.gz"

