#!/bin/bash -e

#©keithhedger Sun 22 Dec 19:34:30 GMT 2019 kdhedger68713@gmail.com

cd /LFSPkgBuildScripts/system/linuxheaders
linuxheaders.LFSBuild up
	
cd /LFSPkgBuilds/LFSPkgBuildScripts/system/glibc
glibc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/binutils
binutils.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/coreutils
coreutils.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/util-linux
util-linux.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/gmp
gmp.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/mpfr
mpfr.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/mpc
mpc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/system/gcc
gcc.LFSBuild up

cd /LFSPkgBuilds/LFSPkgBuildScripts/kernel
kernel.LFSBuild up
firmware.LFSBuild up



