#!/bin/bash
#©keithhedger Sun 20 Oct 15:16:43 BST 2019

. /usr/share/LFSPkg/LFSFunctions

cat >> /etc/ld.so.conf << EOF
# Begin rustc addition

/opt/rust/lib

# End rustc addition
EOF

ldconfig

mkdir -vp /etc/profile.d/||true
cat > /etc/profile.d/rustc.sh << "EOF"
# Begin /etc/profile.d/rustc.sh

pathprepend /opt/rust/bin	PATH

# End /etc/profile.d/rustc.sh
EOF