#!/bin/bash

#©keithhedger Wed 11 Feb 15:55:07 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

pushd /LFSPkgBuilds/LFSPkgBuildScripts/libs/freetype
	./freetype.LFSBuild up
popd

exit 0

