#!/bin/bash

#©keithhedger Wed 11 Feb 15:55:07 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

lfspkg -r FreeType||true
lfspkg -r fontconfig||true
lfspkg -B "fontconfig-2.12.6"

exit 0

