#!/bin/bash

#©keithhedger Wed 11 Feb 15:55:07 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

#lfspkg -r freetype||true
pushd /LFSPkgBuilds/LFSPkgBuildScripts/libs/freetype
	./freetype.LFSBuild up
popd
#lfspkg -B "freetype-2.13.0"||true

exit 0

