#!/bin/bash

#©keithhedger Wed 18 Mar 20:13:22 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

GID=$(findnextgid "system")
groupadd -g $GID kvm||true

chgrp kvm /usr/libexec/qemu-bridge-helper
chmod 4750 /usr/libexec/qemu-bridge-helper
exit 0