#!/bin/bash

BUILD=$1
KERNELVERSION=${2:-"$(uname -r)"}

pushd /boot
	ln -svf config-${KERNELVERSION}-${BUILD} config-${KERNELVERSION}
	ln -svf System.map-${KERNELVERSION}-${BUILD} System.map-${KERNELVERSION}
	ln -svf vmlinuz-${KERNELVERSION}-${BUILD} vmlinuz-${KERNELVERSION}
	ln -svf vmlinuz-${KERNELVERSION}-${BUILD} vmlinuz
popd
pushd /lib/modules
	rm ${KERNELVERSION}
	ln -svf ${KERNELVERSION}-${BUILD} ${KERNELVERSION}
popd

