#!/bin/bash -e

#©keithhedger Wed 28 Jun 11:36:29 BST 2017 kdhedger68713@gmail.com

#Build xorg:
cd /LFSPkgBuildScripts/xorg/xorg-meta/
./xorg-meta.LFSBuild install

#Install documentation stuff
#Also installs python via dependency
#Loads of apps need these for building documentation so might as well install now.
cd /LFSPkgBuildScripts/devel/gtk-doc
./gtk-doc.LFSBuild install

cd /LFSPkgBuildScripts/devel/doxygen
./doxygen.LFSBuild install

#Install cups and gtk.
#Gtk2 has a 'soft' dependency on cups so best to buils cups first.
cd /LFSPkgBuildScripts/print/cups
./cups.LFSBuild install

cd /LFSPkgBuildScripts/gtk/gtk
./gtk.LFSBuild install

#rest of printing stuff
cd /LFSPkgBuildScripts/print/printing-meta
./printing-meta.LFSBuild install

#multi media
cd /LFSPkgBuildScripts/mm/mm-meta
./mm-meta.LFSBuild install

#Development stuff
cd /LFSPkgBuildScripts/devel/development-meta
./development-meta.LFSBuild install

#The big one! build a complete desktop
#this meta packagage includes other meta packages and takes a LOOOooooonnnnggggg time to build!
#this is for an xfce4 desktop.
cd /LFSPkgBuildScripts/desktop/desktop-meta
./desktop-meta.LFSBuild  install
#Or for an LFSDesktop
cd /LFSPkgBuildScripts/lfsdesktop/LFSDesktop-meta
./LFSDesktop-meta.LFSBuild install

#Extra odd stuff
#Chromium
cd /LFSPkgBuildScripts/desktop/chromium
./chromium.LFSBuild install

#Cairo-dock-plugins pulls in cairo-dock as a dependency
cd /LFSPkgBuildScripts/desktop/cairo-dock-plugins
./cairo-dock-plugins.LFSBuild install

#Qemu builds both static and dynamically linked versions
cd /LFSPkgBuildScripts/hware/qemu
./qemu.LFSBuild install

#Seamonkey for web dev
cd /LFSPkgBuildScripts/net/seamonkey
./seamonkey.LFSBuild install

#Icedtea-web
cd /LFSPkgBuildScripts/net/icedtea-web
./icedtea-web.LFSBuild install
#For pulse audio
cd /LFSPkgBuildScripts/net/icedtea-sound
./icedtea-sound.LFSBuild install

#Samba
cd /LFSPkgBuildScripts/net/samba
./samba.LFSBuild install

#Fuse and stuff
cd /LFSPkgBuildScripts/net/sshfs
./sshfs.LFSBuild install

cd /LFSPkgBuildScripts/net/davfs2
./davfs2.LFSBuild install

cd /LFSPkgBuildScripts/net/curlftpfs
./curlftpfs.LFSBuild install

#Qt5 stuff
#cd /LFSPkgBuildScripts/qt/lxqt-meta
#./lxqt-meta.LFSBuild install

#TODO
cd /LFSPkgBuildScripts/qt/qt-creator
./qt-creator.LFSBuild install

cd /LFSPkgBuildScripts/admin/mariadb
./mariadb.LFSBuild install

#Busybox init
#cd /LFSPkgBuildScripts/sys/busybox
#./busybox.LFSBuild install
#
#cd /LFSPkgBuildScripts/sys/bootfiles
#./bootfiles.LFSBuild install

#Odd stuff
cd /LFSPkgBuildScripts/xorg/xbindkeys
./xbindkeys.LFSBuild install

cd /LFSPkgBuildScripts/net/libcddb
./libcddb.LFSBuild install

cd /LFSPkgBuildScripts/desktop/epdfview
./epdfview.LFSBuild install

cd /LFSPkgBuildScripts/desktop/conky
./conky.LFSBuild install


