#!/bin/bash

#©keithhedger Thu 1 Mar 14:05:28 GMT 2018 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

ALPHA=${1:-"a"}
LFSGLOB="${ALPHA}.*"
DATAFILE="/tmp/$$${ALPHA}-site"

links -dump ftp://ftp.lfs-matrix.net/pub/blfs/8.1/$ALPHA > "$DATAFILE"
while read
	do
		if [ "X$(cat "$DATAFILE"|awk '{print $NF}'|grep -v ".patch"|grep "/\b${REPLY}\b")" != "X" ];then
			NEWVERSION="$(cat "$DATAFILE"|awk '{print $NF}'|grep -v ".patch"|grep "/\b${REPLY}\b"|awk -F/ '{print $NF}'|sed -r 's/^.*[-_]([0-9.]+)\..*/\1/')"
			if [ $(echo "$NEWVERSION"|wc -l) -gt 1 ];then
				echo -e "${GREEN}Manually check $(lfspkg -S $REPLY 3) ...${NORMAL}"
				continue
			fi
			OLDVERSION=$(lfspkg -S $REPLY 2)

			if [ $(checkversion $NEWVERSION $OLDVERSION) -ne 0 ];then
				echo -e "${RED}$REPLY needs adjusting ..${NORMAL}"
				lfspkg -S $REPLY 3
				echo
			fi
		fi
	done < <(lfspkg  -S "$LFSGLOB" |sed -n 's/^Package name=\(.*\)/\1/p')

rm $DATAFILE