#!/bin/bash

#. /usr/share/LFSPkg/LFSFunctions
RED='\e[1;31m'
GREEN='\e[1;32m'
BLUE='\e[1;34m'
BLACK='\e[0;30m'
NORMAL='\e[0;0m'


UF="updatefile"
ROOT="$(readlink -f ..)"
lfspkg -R "$ROOT" -U

links http://www.linuxfromscratch.org/lfs/view/8.1/chapter01/whatsnew.html -dump |sed 's/^ *\* *//g'|sed 's/^ *//g' |sed 's/^ *\* *//g' > "$UF"

while read
	do
		pkg=$(echo "$REPLY"|sed 's/^\s*\(.*\) \(.*\)$/\1/')
		if [ X$pkg != "X" ] && [ X$pkg != "XAdded:" ] && [ X$pkg != "XUpgraded" ];then
			if lfspkg -R "$ROOT" -C $pkg 2>&1|grep -i "ok" 2>&1>/dev/null;then
				:
			else
				echo -e "${RED}$pkg${NORMAL} needs up/downgrading to ${BLUE}$(echo "$REPLY"|sed 's/^\s*\(.*\) \(.*\)$/\1-\2/')${NORMAL} from ${RED}${pkg}-$(lfspkg -R "$ROOT" -S $pkg 2)${NORMAL}"
				lfspkg -R "$ROOT" -S $pkg 3
				echo
			fi
		fi
	done < <(sed -n '/^Upgraded to:$/,/^Added/ p' "$UF"|sort)

sed -n '/^Added:$/,/Prev/ p' "$UF"

#lfspkg -P 2>/dev/null|sed 's/^\(More info here:.*\)$/\1\n/g'
