#!/bin/bash

#©keithhedger Sun 25 Apr 13:28:15 BST 2021 kdhedger68713@gmail.com

mkdir -vp /tmp/patches
rm /tmp/patches/*
:>/tmp/patches/REJECTS
:>/tmp/patches/OK
SCRIPTS=/mnt/LFS/LFSPkgBuilds/LFSPkgBuildScripts
#SCRIPTS=/tmp/LFSPkgBuildScripts
cd $SCRIPTS

while read
	do
	#echo $REPLY
		eval $(grep "PKGNAME=" "$REPLY")||true
		eval $(grep "TARNAME=" "$REPLY")||true
		eval $(grep "VERSION=" "$REPLY")||true
		x=$(grep "^[[:space:]]*gettar.*linuxfromscratch.*\.patch" "$REPLY")||true
		if [ "$x" != "" ];then
			y=$(echo ${x/\/blfs\///downloads/}|sed -E 's@/\$\{*LFSVERSION\}*/|/10.1/|/9.0/|/7.5/|7.6/|/8.2/|/7.7/@/${PKGNAME}/@;s@http:@https:@')
			y="${y//\"}"
			y="${y/\$SECTION/}"
			final=$(eval echo ${y/gettar/})
			pushd /tmp/patches
				if ! wget  --timeout=1 --waitretry=0 --tries=2 --retry-connrefused "$final";then
					echo "NO $REPLY ..."
					echo wget $final
					echo "$REPLY $final" >> ./REJECTS
				else
					echo $SCRIPTS/$REPLY >> ./OK
					replace=$(echo ${x/\/blfs\///downloads/}|sed -E 's@/\$\{*LFSVERSION\}*/|/10.1/|/9.0/|/7.5/|7.6/|/8.2/|/7.7/@/${PKGNAME}/@;s@http:@https:@')
					#show only
					sed -n "s@^[[:space:]]*gettar.*linuxfromscratch.*\.patch.*@$replace@p" $SCRIPTS/$REPLY >> ./OK
					#change in place
					#sed -i "s@^[[:space:]]*gettar.*linuxfromscratch.*\.patch.*@$replace@" $SCRIPTS/$REPLY
				fi
			popd
		fi
	done < <(find -iname "*.LFSBuild"|sort)
