#!/bin/bash

mkdir -vp /etc/sgml/ /usr/share/sgml/

install-catalog --remove /etc/sgml/sgml-ent.cat /usr/share/sgml/sgml-iso-entities-8879.1986/catalog||true
install-catalog --remove /etc/sgml/sgml-docbook.cat /etc/sgml/sgml-ent.cat||true

install-catalog --add /etc/sgml/sgml-ent.cat /usr/share/sgml/sgml-iso-entities-8879.1986/catalog
install-catalog --add /etc/sgml/sgml-docbook.cat/etc/sgml/sgml-ent.cat