#!/bin/bash

#©keithhedger Wed 11 Feb 15:18:13 GMT 2015 kdhedger68713@gmail.com


. /usr/share/LFSPkg/LFSFunctions

update-desktop-database -q||true
gtk-update-icon-cache -t -f --include-image-data /usr/share/icons/hicolor||true

exit 0
