#!/bin/bash
#©keithhedger Sat 10 Apr 15:48:43 BST 2021

. /usr/share/LFSPkg/LFSFunctions

UIDGIDPAIR=$(findnextpair "system")
useradd -c "Avahi Daemon Owner" -d /var/run/avahi-daemon -ru $UIDGIDPAIR -s /bin/false avahi||true

NEWGID=$(findnextgid "system")
groupadd -fg $NEWGID netdev||true


