#!/bin/bash -e

#©keithhedger Mon 2 Feb 20:42:33 GMT 2015 kdhedger68713@gmail.com

mkdir -p /etc/default

cat >/etc/default/useradd<<EOF
GROUP=999
HOME=/home
INACTIVE=-1
EXPIRE=
SHELL=/bin/bash
SKEL=/etc/skel
CREATE_MAIL_SPOOL=no
EOF

pwconv
grpconv
