#!/bin/bash
#©keithhedger Fri 20 Jul 13:18:35 BST 2018

. /usr/share/LFSPkg/LFSFunctions

echo $(hostname) > /etc/mail/local-host-names
cat > /etc/mail/aliases << "EOF"
#
#	@(#)aliases	8.2 (Berkeley) 3/5/94
#
#  Aliases in this file will NOT be expanded in the header from
#  Mail, but WILL be visible over networks or from /bin/mail.
#
#	>>>>>>>>>>	The program "newaliases" must be run after
#	>> NOTE >>	this file is updated for any changes to
#	>>>>>>>>>>	show through to sendmail.
#

# Basic system aliases -- these MUST be present.
MAILER-DAEMON:	postmaster
postmaster:	root

# General redirections for pseudo accounts.
bin:		root
daemon:		root
games:		root
ingres:		root
nobody:		root
system:		root
toor:		root
uucp:		root

# Well-known aliases.
manager:	root
dumper:		root
webmaster:      root
abuse:		root

# trap decode to catch security attacks
decode:		root

EOF

newaliases
cd /etc/mail
m4 /usr/share/sendmail/cf/m4/cf.m4 sendmail.mc > sendmail.cf

