#!/bin/bash -e

#©keithhedger Thu 19 Feb 15:49:20 GMT 2015 kdhedger68713@gmail.com

/usr/sbin/update-pciids

mkdir -vp /etc/cron.weekly ||true
cat > /etc/cron.weekly/update-pciids.sh << "EOF"
#!/bin/bash
/usr/sbin/update-pciids
EOF
chmod 754 /etc/cron.weekly/update-pciids.sh