#!/bin/bash

#©keithhedger Mon 2 Feb 13:56:56 GMT 2015 kdhedger68713@gmail.com

if [ -e ./SystemData ];then
	. ./SystemData
else
	echo "No SystemData file found ..."
	exit 0
fi

pushd $LFS
	mount -v --bind /dev dev
	mount -vt proc proc proc
	mount -vt sysfs sysfs sys

	if [ -e dev/shm ];then
		mkdir -pv $(readlink dev/shm)
	fi

#extra folders from the host can be mounted either from here or from the chroot environment
#dont forget to add the unmount commands to the AfterExitChroot script or unmount them before leaving the chroot.
#you will probably need both of these ( see the how to )
#this is the folder for the source archives:

	mkdir -vp ${LFS}/${SOURCEARCHIVES}||true
	mkdir -vp ${LFS}/${BUILTPACKAGES}||true
	if [ "X$EXTFOLDER" != "X" ];then
		mount --bind $EXTFOLDER/${BUILTPACKAGES} $LFS/${BUILTPACKAGES}
		mount --bind $EXTFOLDER/${SOURCEARCHIVES} $LFS/${SOURCEARCHIVES}
	fi

#This seems to be needed now as TERM=xterm screws up ncurses
#Set TERM as dialog needs it
	export TERM="xterm-color"
	if [ X$1 = "Xsystem" ];then
		chroot "$LFS" /tools/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin /tools/bin/bash --login +h
	else
		chroot "$LFS" /usr/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login
	fi
popd

./AfterExitChroot
