#!/bin/bash

#©keithhedger Mon 2 Feb 13:56:56 GMT 2015 kdhedger68713@gmail.com

if [ -e ./SystemData ];then
	. ./SystemData
else
	echo "No SystemData file found ..."
	exit 0
fi
LFS=/media/LFSBomb20

pushd $LFS
	mount -v --bind /dev $LFS/dev
	mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
	mount -vt proc proc $LFS/proc
	mount -vt sysfs sysfs $LFS/sys
	mount -vt tmpfs tmpfs $LFS/run

	if [ -h $LFS/dev/shm ];then
		mkdir -pv $LFS/$(readlink $LFS/dev/shm)
	fi

#extra folders from the host can be mounted either from here or from the chroot environment
#dont forget to add the unmount commands to the AfterExitChroot script or unmount them before leaving the chroot.
#you will probably need both of these ( see the how to )
#this is the folder for the source archives:

	mkdir -vp ${LFS}/${SOURCEARCHIVES}||true
	mkdir -vp ${LFS}/${BUILTPACKAGES}||true
	if [ "X$EXTFOLDER" != "X" ];then
		mount --bind $EXTFOLDER/${BUILTPACKAGES} $LFS/${BUILTPACKAGES}
		mount --bind $EXTFOLDER/${SOURCEARCHIVES} $LFS/${SOURCEARCHIVES}
	fi

#	mkdir -vp ${LFS}/${SOURCEARCHIVES}||true
#	mount --bind ${SOURCEARCHIVES} ${LFS}/${SOURCEARCHIVES}

#This seems to be needed now as TERM=xterm screws up ncurses
#Set TERM as dialog needs it
	export TERM="xterm-color"
	if [ X$1 = "Xsystem" ];then
		mv ${LFS}/etc/profile ${LFS}/etc/profile.BAK
		chroot "$LFS" /tools/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin /tools/bin/bash --login +h
		mv ${LFS}/etc/profile.BAK ${LFS}/etc/profile
	else
		chroot "$LFS" /usr/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login
	fi
popd

./AfterExitChroot
