#!/bin/bash

#©keithhedger Mon 2 Feb 12:38:29 GMT 2015 kdhedger68713@gmail.com

#Add any extra info you want here

if [ -e "SystemData.local" ];then
	. "SystemData.local"
fi

#Add any extra info you want here
