#!/bin/bash -e

#©keithhedger Tue 17 Mar 13:49:42 GMT 2015 kdhedger68713@gmail.com

if [ -e ./SystemData ];then
	. ./SystemData
else
	echo "No SystemData file found ..."
	exit 0
fi

while read
	do
		sed -r -i 's/\bBUILD=.*\b/BUILD=${BUILD:-1}/' ${REPLY}
	done < <(find ${LFS}/LFSPkgBuildScripts -iname "*.LFSBuild")