#!/bin/bash
#©keithhedger Sat 18 Jul 19:14:57 BST 2020

. /usr/share/LFSPkg/LFSFunctions

UIDGIDPAIR=$(findnextpair "system")
groupadd -g $UIDGIDPAIR ntop||true
useradd -c "NTop User" -d /var/lib/ntop -s /bin/false -g ntop -s /bin/false -u $UIDGIDPAIR ntop||true
chown -R ntop:ntop /var/lib/ntop
