#!/bin/bash

#©keithhedger Thu 3 Dec 12:26:07 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions
. /LFSScripts/PkgVersions

TZDATATARBALL=${SOURCEARCHIVES}/${SECTION}/tzdata${TZDATA_VERS}.tar.gz

cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf

/usr/lib64/qt5
/usr/lib/qt5

/usr/local/lib
/opt/lib

include /etc/ld.so.conf.d/*.conf
/usr/lib
EOF

pushd $COMPILEAT 2>/dev/null||true
	mkdir build||true
	pushd build
		tar -xf ${TZDATATARBALL}
		ZONEINFO="/usr/share/zoneinfo"
		mkdir -pv $ZONEINFO/{posix,right}

		for tz in etcetera southamerica northamerica europe africa antarctica asia australasia backward pacificnew systemv
		do
			zic -L /dev/null   -d $ZONEINFO -y "sh yearistype.sh" ${tz}
			zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz}
			zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz}
		done

		cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
		zic -d $ZONEINFO -p Europe/London
		unset ZONEINFO
		cp -v /usr/share/zoneinfo/Europe/London /etc/localtime
	popd
	rm -rf build
popd

#locales
localedef -i de_DE -f ISO-8859-1 de_DE
localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
localedef -i de_DE -f UTF-8 de_DE.UTF-8
localedef -i en_GB -f ISO-8859-1 en_GB
localedef -i en_GB -f UTF-8 en_GB.UTF-8
localedef -i en_HK -f ISO-8859-1 en_HK
localedef -i en_PH -f ISO-8859-1 en_PH
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i fr_FR -f ISO-8859-1 fr_FR
localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
