#!/bin/bash

#©keithhedger Tue 3 Feb 19:40:19 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

cat > /etc/pam.d/polkit-1 << "EOF"
# Begin /etc/pam.d/polkit-1

auth     include        system-auth
account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/polkit-1
EOF