#!/bin/bash -e

#©keithhedger Thu 19 Feb 13:05:33 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

QT5PREFIX=${QT5PREFIX:-/usr}

cat > /etc/profile.d/qt5.sh << EOF
# Begin /etc/profile.d/qt5.sh

QT5PREFIX=${QT5PREFIX}
export QT5PREFIX

pathappend \${QT5PREFIX}/bin

# End /etc/profile.d/qt5.sh
EOF

mkdir -vp /etc/pango ||true
/usr/bin/gdk-pixbuf-query-loaders --update-cache||true
fc-cache -f||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/hicolor||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/gnome||true
update-mime-database /usr/share/mime||true
mkdir -vp /var/cache/man/fsstnd||true
mandb -c||true



