#!/bin/bash -e

#©keithhedger Thu 19 Feb 13:05:33 GMT 2015 kdhedger68713@gmail.com

. /usr/share/LFSPkg/LFSFunctions

QT5DIR=${QT5DIR:-/usr}

cat > /etc/profile.d/qt5.sh << EOF
# Begin /etc/profile.d/qt5.sh

QT5DIR=${QT5DIR}
export QT5DIR

pathappend $QT5DIR/bin

# End /etc/profile.d/qt5.sh
EOF

if [ ! "$(grep -i "${QT5DIR}" /etc/ld.so.conf)" ];then
	echo "${QT5DIR}" >> /etc/ld.so.conf
	ldconfig||true
fi

mkdir -vp /etc/pango ||true
/usr/bin/gdk-pixbuf-query-loaders --update-cache||true
fc-cache -f||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/hicolor||true
gtk-update-icon-cache --ignore-theme-index --force /usr/share/icons/gnome||true
update-mime-database /usr/share/mime||true
mkdir -vp /var/cache/man/fsstnd||true
mandb -c||true



