#!/bin/bash

#©keithhedger Tue 3 Feb 19:40:19 GMT 2015 kdhedger68713@gmail.com

rm -f /usr/bin/xsltproc||true
systemd-machine-id-setup
rm -fv /usr/lib/lib{blkid,uuid,mount}.so*||true
rm -f /usr/lib/tmpfiles.d/systemd-nologin.conf||true
